# import python modules
import os
from win32com.client import Dispatch
# Connecting to windows COM 
CATIA = Dispatch('CATIA.Application')
# optional CATIA visibility
CATIA.Visible = True

a=31.25
b=68.75
c=55
d=50
e=25
f=175
g=60
h=25
m=200

def knuckles():
    arrayOfVariantOfDouble1=[0,0,0,0,0,0,0,0,0]
    arrayOfVariantOfDouble2=[0,0,0,0,0,0,0,0,0]
    arrayOfVariantOfDouble3=[0,0,0,0,0,0,0,0,0]
    arrayOfVariantOfDouble4=[0,0,0,0,0,0,0,0,0]
    arrayOfVariantOfDouble5=[0,0,0,0,0,0,0,0,0]
    
    documents1 = CATIA.Documents
    partDocument1 = documents1.Add('Part')
    part1 = partDocument1.Part
    hybridBodies1 = part1.HybridBodies
    hybridBody1 = hybridBodies1.Item('Geometrical Set.1')
    sketches1 = hybridBody1.HybridSketches
    originElements1 = part1.OriginElements
    reference1 = originElements1.PlaneZX
    sketch1 = sketches1.Add(reference1)
    arrayOfVariantOfDouble1[0] = 0.000000
    arrayOfVariantOfDouble1[1] = 0.000000
    arrayOfVariantOfDouble1[2] = 0.000000
    arrayOfVariantOfDouble1[3] = - 1.000000
    arrayOfVariantOfDouble1[4] = 0.000000
    arrayOfVariantOfDouble1[5] = 0.000000
    arrayOfVariantOfDouble1[6] = 0.000000
    arrayOfVariantOfDouble1[7] = - 0.000000
    arrayOfVariantOfDouble1[8] = 1.000000
    sketch1.SetAbsoluteAxisData(arrayOfVariantOfDouble1)
    part1.InWorkObject = sketch1
    factory2D1 = sketch1.OpenEdition()                                   #sketch 1 opened
    geometricElements1 = sketch1.GeometricElements
    axis2D1 = geometricElements1.Item('AbsoluteAxis')
    line2D1 = axis2D1.GetItem('HDirection')
    line2D1.ReportName = 1
    line2D2 = axis2D1.GetItem('VDirection')
    line2D2.ReportName = 2
    point2D1 = factory2D1.CreatePoint(0, 0)
    point2D1.ReportName = 3
    circle2D1 = factory2D1.CreateClosedCircle(0.000000, 0, d)     #diameter of outer(d)
    circle2D1.CenterPoint = point2D1
    circle2D1.ReportName = 4
    constraints1 = sketch1.Constraints
    reference2 = part1.CreateReferenceFromObject(point2D1)
    reference3 = part1.CreateReferenceFromObject(line2D2)
    #onstraint1 = constraints1.AddBiEltCst(catCstTypeOn, reference2, reference3)
    #constraint1.Mode = catCstModeDrivingDimension
    point2D2 = factory2D1.CreatePoint(d, 0.000000)
    point2D2.ReportName = 5
    reference4 = part1.CreateReferenceFromObject(circle2D1)
    reference5 = part1.CreateReferenceFromObject(point2D2)
    #constraint2 = constraints1.AddBiEltCst(catCstTypeOn, reference4, reference5)
    #constraint2.Mode = catCstModeDrivingDimension
    reference6 = part1.CreateReferenceFromObject(point2D2)
    reference7 = part1.CreateReferenceFromObject(line2D1)
    #constraint3 = constraints1.AddBiEltCst(catCstTypeOn, reference6, reference7)
    #constraint3.Mode = catCstModeDrivingDimension
    sketch1.CloseEdition()                                                        #sketch 1 closed
    part1.InWorkObject = hybridBody1
    part1.Update()
    bodies1 = part1.Bodies
    body1 = bodies1.Item('PartBody')
    part1.InWorkObject = body1
    part1.InWorkObject = body1
    shapeFactory1 = part1.ShapeFactory
    reference8 = part1.CreateReferenceFromName('')
    pad1 = shapeFactory1.AddNewPadFromRef(reference8, 20.000000)
    reference9 = part1.CreateReferenceFromObject(sketch1)
    pad1.SetProfileElement(reference9)
    pad1.IsSymmetric = True
    limit1 = pad1.FirstLimit
    length1 = limit1.Dimension
    length1.Value = 31.250000
    part1.Update()

    
    sketches2 = body1.Sketches
    sketch2 = sketches2.Add(reference1)
    arrayOfVariantOfDouble2[0] = 0.000000
    arrayOfVariantOfDouble2[1] = 0.000000
    arrayOfVariantOfDouble2[2] = 0.000000
    arrayOfVariantOfDouble2[3] = - 1.000000
    arrayOfVariantOfDouble2[4] = 0.000000
    arrayOfVariantOfDouble2[5] = 0.000000
    arrayOfVariantOfDouble2[6] = 0.000000
    arrayOfVariantOfDouble2[7] = - 0.000000
    arrayOfVariantOfDouble2[8] = 1.000000
    sketch2.SetAbsoluteAxisData(arrayOfVariantOfDouble2)
    part1.InWorkObject = sketch2
    factory2D2 = sketch2.OpenEdition()                                               #sketch 2 opened
    geometricElements2 = sketch2.GeometricElements
    axis2D2 = geometricElements2.Item('AbsoluteAxis')
    line2D3 = axis2D2.GetItem('HDirection')
    line2D3.ReportName = 1
    line2D4 = axis2D2.GetItem('VDirection')
    line2D4.ReportName = 2
    point2D3 = factory2D2.CreatePoint(0.000000, 0.000000)
    point2D3.ReportName = 3
    point2D4 = factory2D2.CreatePoint(0.000000, (c/2))
    point2D4.ReportName = 4
    line2D5 = factory2D2.CreateLine(0.000000, 0.000000, 0.000000, (c/2))
    line2D5.ReportName = 5
    line2D5.StartPoint = point2D3
    line2D5.EndPoint = point2D4
    constraints2 = sketch2.Constraints
    reference10 = part1.CreateReferenceFromObject(point2D3)
    reference11 = part1.CreateReferenceFromObject(line2D4)
    #constraint4 = constraints2.AddBiEltCst(catCstTypeDistance, reference10, reference11)
    #constraint4.Mode = catCstModeDrivingDimension
    #length2 = constraint4.Dimension
    #length2.Value = 0.000000
    reference12 = part1.CreateReferenceFromObject(point2D3)
    reference13 = part1.CreateReferenceFromObject(line2D3)
    #constraint5 = constraints2.AddBiEltCst(catCstTypeDistance, reference12, reference13)
    #constraint5.Mode = catCstModeDrivingDimension
    #length3 = constraint5.Dimension
    #length3.Value = 0.000000
    reference14 = part1.CreateReferenceFromObject(point2D4)
    reference15 = part1.CreateReferenceFromObject(line2D4)
    #constraint6 = constraints2.AddBiEltCst(catCstTypeDistance, reference14, reference15)
    #constraint6.Mode = catCstModeDrivingDimension
    #length4 = constraint6.Dimension
    #length4.Value = 0.000000
    reference16 = part1.CreateReferenceFromObject(point2D4)
    reference17 = part1.CreateReferenceFromObject(line2D3)
    #constraint7 = constraints2.AddBiEltCst(catCstTypeDistance, reference16, reference17)
    #constraint7.Mode = catCstModeDrivingDimension
    #length5 = constraint7.Dimension
    #length5.Value = 27.500000
    point2D5 = factory2D2.CreatePoint(0.000000, (c/2))
    point2D5.ReportName = 6
    point2D6 = factory2D2.CreatePoint(m, (c/2))           #m is a 4.5kd
    point2D6.ReportName = 7
    line2D6 = factory2D2.CreateLine(0.000000, (c/2), m, (c/2))
    line2D6.ReportName = 8
    line2D6.StartPoint = point2D5
    line2D6.EndPoint = point2D6
    reference18 = part1.CreateReferenceFromObject(point2D5)
    reference19 = part1.CreateReferenceFromObject(line2D4)
    #constraint8 = constraints2.AddBiEltCst(catCstTypeDistance, reference18, reference19)
    #constraint8.Mode = catCstModeDrivingDimension
    #length6 = constraint8.Dimension
    #length6.Value = 0.000000
    reference20 = part1.CreateReferenceFromObject(point2D5)
    reference21 = part1.CreateReferenceFromObject(line2D3)
    #constraint9 = constraints2.AddBiEltCst(catCstTypeDistance, reference20, reference21)
    #constraint9.Mode = catCstModeDrivingDimension
    #length7 = constraint9.Dimension
    #length7.Value = 27.500000
    reference22 = part1.CreateReferenceFromObject(point2D6)
    reference23 = part1.CreateReferenceFromObject(line2D4)
    #constraint10 = constraints2.AddBiEltCst(catCstTypeDistance, reference22, reference23)
    #constraint10.Mode = catCstModeDrivingDimension
    #length8 = constraint10.Dimension
    #length8.Value = 225.000000
    reference24 = part1.CreateReferenceFromObject(point2D6)
    reference25 = part1.CreateReferenceFromObject(line2D3)
    #constraint11 = constraints2.AddBiEltCst(catCstTypeDistance, reference24, reference25)
    #constraint11.Mode = catCstModeDrivingDimension
    #length9 = constraint11.Dimension
    #length9.Value = 27.500000
    point2D7 = factory2D2.CreatePoint(m, (c/2))
    point2D7.ReportName = 9
    point2D8 = factory2D2.CreatePoint(m, - (c/2))
    point2D8.ReportName = 10
    line2D7 = factory2D2.CreateLine(m, (c/2), m, - (c/2))
    line2D7.ReportName = 11
    line2D7.StartPoint = point2D7
    line2D7.EndPoint = point2D8
    reference26 = part1.CreateReferenceFromObject(point2D7)
    reference27 = part1.CreateReferenceFromObject(line2D4)
    #constraint12 = constraints2.AddBiEltCst(catCstTypeDistance, reference26, reference27)
    #constraint12.Mode = catCstModeDrivingDimension
    #length10 = constraint12.Dimension
    #length10.Value = 225.000000
    reference28 = part1.CreateReferenceFromObject(point2D7)
    reference29 = part1.CreateReferenceFromObject(line2D3)
    #constraint13 = constraints2.AddBiEltCst(catCstTypeDistance, reference28, reference29)
    #constraint13.Mode = catCstModeDrivingDimension
    #length11 = constraint13.Dimension
    #length11.Value = 27.500000
    reference30 = part1.CreateReferenceFromObject(point2D8)
    reference31 = part1.CreateReferenceFromObject(line2D4)
    #constraint14 = constraints2.AddBiEltCst(catCstTypeDistance, reference30, reference31)
    #constraint14.Mode = catCstModeDrivingDimension
    #length12 = constraint14.Dimension
    #length12.Value = 225.000000
    reference32 = part1.CreateReferenceFromObject(point2D8)
    reference33 = part1.CreateReferenceFromObject(line2D3)
    #constraint15 = constraints2.AddBiEltCst(catCstTypeDistance, reference32, reference33)
    #constraint15.Mode = catCstModeDrivingDimension
    #length13 = constraint15.Dimension
    #length13.Value = 27.500000
    point2D9 = factory2D2.CreatePoint(m, - (c/2))
    point2D9.ReportName = 12
    point2D10 = factory2D2.CreatePoint(0.000000, - (c/2))
    point2D10.ReportName = 13
    line2D8 = factory2D2.CreateLine(m, - (c/2), 0.000000, - (c/2))
    line2D8.ReportName = 14
    line2D8.StartPoint = point2D9
    line2D8.EndPoint = point2D10
    reference34 = part1.CreateReferenceFromObject(point2D9)
    reference35 = part1.CreateReferenceFromObject(line2D4)
    #constraint16 = constraints2.AddBiEltCst(catCstTypeDistance, reference34, reference35)
    #constraint16.Mode = catCstModeDrivingDimension
    #length14 = constraint16.Dimension
    #length14.Value = 225.000000
    reference36 = part1.CreateReferenceFromObject(point2D9)
    reference37 = part1.CreateReferenceFromObject(line2D3)
    #constraint17 = constraints2.AddBiEltCst(catCstTypeDistance, reference36, reference37)
    #constraint17.Mode = catCstModeDrivingDimension
    #length15 = constraint17.Dimension
    #length15.Value = 27.500000
    reference38 = part1.CreateReferenceFromObject(point2D10)
    reference39 = part1.CreateReferenceFromObject(line2D4)
    #constraint18 = constraints2.AddBiEltCst(catCstTypeDistance, reference38, reference39)
    #constraint18.Mode = catCstModeDrivingDimension
    #length16 = constraint18.Dimension
    #length16.Value = 0.000000
    reference40 = part1.CreateReferenceFromObject(point2D10)
    reference41 = part1.CreateReferenceFromObject(line2D3)
    #constraint19 = constraints2.AddBiEltCst(catCstTypeDistance, reference40, reference41)
    #constraint19.Mode = catCstModeDrivingDimension
    #length17 = constraint19.Dimension
    #length17.Value = 27.500000
    point2D11 = factory2D2.CreatePoint(0.000000, - (c/2))
    point2D11.ReportName = 15
    point2D12 = factory2D2.CreatePoint(0.000000, 0.000000)
    point2D12.ReportName = 16
    line2D9 = factory2D2.CreateLine(0.000000, - (c/2), 0.000000, 0.000000)
    line2D9.ReportName = 17
    line2D9.StartPoint = point2D11
    line2D9.EndPoint = point2D12
    reference42 = part1.CreateReferenceFromObject(point2D11)
    reference43 = part1.CreateReferenceFromObject(line2D4)
    #constraint20 = constraints2.AddBiEltCst(catCstTypeDistance, reference42, reference43)
    #constraint20.Mode = catCstModeDrivingDimension
    #length18 = constraint20.Dimension
    #length18.Value = 0.000000
    reference44 = part1.CreateReferenceFromObject(point2D11)
    reference45 = part1.CreateReferenceFromObject(line2D3)
    #constraint21 = constraints2.AddBiEltCst(catCstTypeDistance, reference44, reference45)
    #constraint21.Mode = catCstModeDrivingDimension
    #length19 = constraint21.Dimension
    #length19.Value = 27.500000
    reference46 = part1.CreateReferenceFromObject(point2D12)
    reference47 = part1.CreateReferenceFromObject(line2D4)
    #constraint22 = constraints2.AddBiEltCst(catCstTypeDistance, reference46, reference47)
    #constraint22.Mode = catCstModeDrivingDimension
    #length20 = constraint22.Dimension
    #length20.Value = 0.000000
    reference48 = part1.CreateReferenceFromObject(point2D12)
    reference49 = part1.CreateReferenceFromObject(line2D3)
    #constraint23 = constraints2.AddBiEltCst(catCstTypeDistance, reference48, reference49)
    #constraint23.Mode = catCstModeDrivingDimension
    #length21 = constraint23.Dimension
    #length21.Value = 0.000000
    sketch2.CloseEdition()                                                                         #sketch 2 closed
    part1.InWorkObject = sketch2
    part1.Update()
    reference50 = part1.CreateReferenceFromName('')
    pad2 = shapeFactory1.AddNewPadFromRef(reference50, 31.250000)
    reference51 = part1.CreateReferenceFromObject(sketch2)
    pad2.SetProfileElement(reference51)
    pad2.IsSymmetric = True
    limit2 = pad2.FirstLimit
    length22 = limit2.Dimension
    length22.Value = (c/2)                                                         #c=1.1kd1
    part1.Update()
    specsAndGeomWindow1 = CATIA.ActiveWindow
    viewer3D1 = specsAndGeomWindow1.ActiveViewer
    viewpoint3D1 = viewer3D1.Viewpoint3D
    viewpoint3D1 = viewer3D1.Viewpoint3D
    viewpoint3D1 = viewer3D1.Viewpoint3D

    
    reference52 = part1.CreateReferenceFromName('Selection_RSur:(Face:(Brp:(Pad.2;0:(Brp:(Sketch.2;11)));None:();Cf11:());Pad.2_ResultOUT;Z0;G3563)')
    sketch3 = sketches2.Add(reference52)
    arrayOfVariantOfDouble3[0] = - m
    arrayOfVariantOfDouble3[1] = 0.000000
    arrayOfVariantOfDouble3[2] = 0.000000
    arrayOfVariantOfDouble3[3] = 0.000000
    arrayOfVariantOfDouble3[4] = - 1.000000
    arrayOfVariantOfDouble3[5] = 0.000000
    arrayOfVariantOfDouble3[6] = 0.000000
    arrayOfVariantOfDouble3[7] = 0.000000
    arrayOfVariantOfDouble3[8] = 1.000000
    sketch3.SetAbsoluteAxisData(arrayOfVariantOfDouble3)
    part1.InWorkObject = sketch3
    factory2D3 = sketch3.OpenEdition()                                                             #sketch 3 opened
    geometricElements3 = sketch3.GeometricElements
    axis2D3 = geometricElements3.Item('AbsoluteAxis')
    line2D10 = axis2D3.GetItem('HDirection')
    line2D10.ReportName = 1
    line2D11 = axis2D3.GetItem('VDirection')
    line2D11.ReportName = 2
    point2D13 = factory2D3.CreatePoint((c/2), (c/2))
    point2D13.ReportName = 3
    point2D14 = factory2D3.CreatePoint((c/2), (c/4))
    point2D14.ReportName = 4
    line2D12 = factory2D3.CreateLine((c/2), (c/2), (c/2), (c/4))
    line2D12.ReportName = 5
    line2D12.StartPoint = point2D13
    line2D12.EndPoint = point2D14
    constraints3 = sketch3.Constraints
    reference53 = part1.CreateReferenceFromObject(point2D13)
    reference54 = part1.CreateReferenceFromObject(line2D11)
    #constraint24 = constraints3.AddBiEltCst(catCstTypeDistance, reference53, reference54)
    #constraint24.Mode = catCstModeDrivingDimension
    #length23 = constraint24.Dimension
    #length23.Value = 27.500000
    reference55 = part1.CreateReferenceFromObject(point2D13)
    reference56 = part1.CreateReferenceFromObject(line2D10)
    #constraint25 = constraints3.AddBiEltCst(catCstTypeDistance, reference55, reference56)
    #constraint25.Mode = catCstModeDrivingDimension
    #length24 = constraint25.Dimension
    #length24.Value = 27.500000
    reference57 = part1.CreateReferenceFromObject(point2D14)
    reference58 = part1.CreateReferenceFromObject(line2D11)
    #constraint26 = constraints3.AddBiEltCst(catCstTypeDistance, reference57, reference58)
    #constraint26.Mode = catCstModeDrivingDimension
    #length25 = constraint26.Dimension
    #length25.Value = 27.500000
    reference59 = part1.CreateReferenceFromObject(point2D14)
    reference60 = part1.CreateReferenceFromObject(line2D10)
    #constraint27 = constraints3.AddBiEltCst(catCstTypeDistance, reference59, reference60)
    #constraint27.Mode = catCstModeDrivingDimension
    #length26 = constraint27.Dimension
    #length26.Value = 13.750000
    point2D15 = factory2D3.CreatePoint((c/2), (c/2))
    point2D15.ReportName = 6
    point2D16 = factory2D3.CreatePoint((c/4), (c/2))
    point2D16.ReportName = 7
    line2D13 = factory2D3.CreateLine((c/2), (c/2), (c/4), (c/2))
    line2D13.ReportName = 8
    line2D13.StartPoint = point2D15
    line2D13.EndPoint = point2D16
    reference61 = part1.CreateReferenceFromObject(point2D15)
    reference62 = part1.CreateReferenceFromObject(line2D11)
    #constraint28 = constraints3.AddBiEltCst(catCstTypeDistance, reference61, reference62)
    #constraint28.Mode = catCstModeDrivingDimension
    #length27 = constraint28.Dimension
    #length27.Value = 27.500000
    reference63 = part1.CreateReferenceFromObject(point2D15)
    reference64 = part1.CreateReferenceFromObject(line2D10)
    #constraint29 = constraints3.AddBiEltCst(catCstTypeDistance, reference63, reference64)
    #constraint29.Mode = catCstModeDrivingDimension
    #length28 = constraint29.Dimension
    #length28.Value = 27.500000
    reference65 = part1.CreateReferenceFromObject(point2D16)
    reference66 = part1.CreateReferenceFromObject(line2D11)
    #constraint30 = constraints3.AddBiEltCst(catCstTypeDistance, reference65, reference66)
    #constraint30.Mode = catCstModeDrivingDimension
    #length29 = constraint30.Dimension
    #length29.Value = 13.750000
    reference67 = part1.CreateReferenceFromObject(point2D16)
    reference68 = part1.CreateReferenceFromObject(line2D10)
    #constraint31 = constraints3.AddBiEltCst(catCstTypeDistance, reference67, reference68)
    #constraint31.Mode = catCstModeDrivingDimension
    #length30 = constraint31.Dimension
    #length30.Value = 27.500000
    point2D17 = factory2D3.CreatePoint(- (c/2), (c/2))
    point2D17.ReportName = 9
    point2D18 = factory2D3.CreatePoint(- (c/2), (c/4))
    point2D18.ReportName = 10
    line2D14 = factory2D3.CreateLine(- (c/2), (c/2), - (c/2), (c/4))
    line2D14.ReportName = 11
    line2D14.StartPoint = point2D17
    line2D14.EndPoint = point2D18
    reference69 = part1.CreateReferenceFromObject(point2D17)
    reference70 = part1.CreateReferenceFromObject(line2D11)
    #constraint32 = constraints3.AddBiEltCst(catCstTypeDistance, reference69, reference70)
    #constraint32.Mode = catCstModeDrivingDimension
    #length31 = constraint32.Dimension
    #length31.Value = 27.500000
    reference71 = part1.CreateReferenceFromObject(point2D17)
    reference72 = part1.CreateReferenceFromObject(line2D10)
    #constraint33 = constraints3.AddBiEltCst(catCstTypeDistance, reference71, reference72)
    #constraint33.Mode = catCstModeDrivingDimension
    #length32 = constraint33.Dimension
    #length32.Value = 27.500000
    reference73 = part1.CreateReferenceFromObject(point2D18)
    reference74 = part1.CreateReferenceFromObject(line2D11)
    #constraint34 = constraints3.AddBiEltCst(catCstTypeDistance, reference73, reference74)
    #constraint34.Mode = catCstModeDrivingDimension
    #length33 = constraint34.Dimension
    #length33.Value = 27.500000
    reference75 = part1.CreateReferenceFromObject(point2D18)
    reference76 = part1.CreateReferenceFromObject(line2D10)
    #constraint35 = constraints3.AddBiEltCst(catCstTypeDistance, reference75, reference76)
    #constraint35.Mode = catCstModeDrivingDimension
    #length34 = constraint35.Dimension
    #length34.Value = 13.750000
    point2D19 = factory2D3.CreatePoint(- (c/2), (c/2))
    point2D19.ReportName = 12
    point2D20 = factory2D3.CreatePoint(- (c/4), (c/2))
    point2D20.ReportName = 13
    line2D15 = factory2D3.CreateLine(- (c/2), (c/2), - (c/4), (c/2))
    line2D15.ReportName = 14
    line2D15.StartPoint = point2D19
    line2D15.EndPoint = point2D20
    reference77 = part1.CreateReferenceFromObject(point2D19)
    reference78 = part1.CreateReferenceFromObject(line2D11)
    #constraint36 = constraints3.AddBiEltCst(catCstTypeDistance, reference77, reference78)
    #constraint36.Mode = catCstModeDrivingDimension
    #length35 = constraint36.Dimension
    #length35.Value = 27.500000
    reference79 = part1.CreateReferenceFromObject(point2D19)
    reference80 = part1.CreateReferenceFromObject(line2D10)
    #constraint37 = constraints3.AddBiEltCst(catCstTypeDistance, reference79, reference80)
    #constraint37.Mode = catCstModeDrivingDimension
    #length36 = constraint37.Dimension
    #length36.Value = 27.500000
    reference81 = part1.CreateReferenceFromObject(point2D20)
    reference82 = part1.CreateReferenceFromObject(line2D11)
    #constraint38 = constraints3.AddBiEltCst(catCstTypeDistance, reference81, reference82)
    #constraint38.Mode = catCstModeDrivingDimension
    #length37 = constraint38.Dimension
    #length37.Value = 13.750000
    reference83 = part1.CreateReferenceFromObject(point2D20)
    reference84 = part1.CreateReferenceFromObject(line2D10)
    #constraint39 = constraints3.AddBiEltCst(catCstTypeDistance, reference83, reference84)
    #constraint39.Mode = catCstModeDrivingDimension
    #length38 = constraint39.Dimension
    #length38.Value = 27.500000
    point2D21 = factory2D3.CreatePoint(- (c/2), - (c/2))
    point2D21.ReportName = 15
    point2D22 = factory2D3.CreatePoint(- (c/2), - (c/4))
    point2D22.ReportName = 16
    line2D16 = factory2D3.CreateLine(- (c/2), - (c/2), - (c/2), - (c/4))
    line2D16.ReportName = 17
    line2D16.StartPoint = point2D21
    line2D16.EndPoint = point2D22
    reference85 = part1.CreateReferenceFromObject(point2D21)
    reference86 = part1.CreateReferenceFromObject(line2D11)
    #constraint40 = constraints3.AddBiEltCst(catCstTypeDistance, reference85, reference86)
    #constraint40.Mode = catCstModeDrivingDimension
    #length39 = constraint40.Dimension
    #length39.Value = 27.500000
    reference87 = part1.CreateReferenceFromObject(point2D21)
    reference88 = part1.CreateReferenceFromObject(line2D10)
    #constraint41 = constraints3.AddBiEltCst(catCstTypeDistance, reference87, reference88)
    #constraint41.Mode = catCstModeDrivingDimension
    #length40 = constraint41.Dimension
    #length40.Value = 27.500000
    reference89 = part1.CreateReferenceFromObject(point2D22)
    reference90 = part1.CreateReferenceFromObject(line2D11)
    #constraint42 = constraints3.AddBiEltCst(catCstTypeDistance, reference89, reference90)
    #constraint42.Mode = catCstModeDrivingDimension
    #length41 = constraint42.Dimension
    #length41.Value = 27.500000
    reference91 = part1.CreateReferenceFromObject(point2D22)
    reference92 = part1.CreateReferenceFromObject(line2D10)
    #constraint43 = constraints3.AddBiEltCst(catCstTypeDistance, reference91, reference92)
    #constraint43.Mode = catCstModeDrivingDimension
    #length42 = constraint43.Dimension
    #length42.Value = 13.750000
    point2D23 = factory2D3.CreatePoint(- (c/2), - (c/2))
    point2D23.ReportName = 18
    point2D24 = factory2D3.CreatePoint(- (c/4), - (c/2))
    point2D24.ReportName = 19
    line2D17 = factory2D3.CreateLine(- (c/2), - (c/2), - (c/4), - (c/2))
    line2D17.ReportName = 20
    line2D17.StartPoint = point2D23
    line2D17.EndPoint = point2D24
    reference93 = part1.CreateReferenceFromObject(point2D23)
    reference94 = part1.CreateReferenceFromObject(line2D11)
    #constraint44 = constraints3.AddBiEltCst(catCstTypeDistance, reference93, reference94)
    #constraint44.Mode = catCstModeDrivingDimension
    #length43 = constraint44.Dimension
    #length43.Value = 27.500000
    reference95 = part1.CreateReferenceFromObject(point2D23)
    reference96 = part1.CreateReferenceFromObject(line2D10)
    #constraint45 = constraints3.AddBiEltCst(catCstTypeDistance, reference95, reference96)
    #constraint45.Mode = catCstModeDrivingDimension
    #length44 = constraint45.Dimension
    #length44.Value = 27.500000
    reference97 = part1.CreateReferenceFromObject(point2D24)
    reference98 = part1.CreateReferenceFromObject(line2D11)
    #constraint46 = constraints3.AddBiEltCst(catCstTypeDistance, reference97, reference98)
    #constraint46.Mode = catCstModeDrivingDimension
    #length45 = constraint46.Dimension
    #length45.Value = 13.750000
    reference99 = part1.CreateReferenceFromObject(point2D24)
    reference100 = part1.CreateReferenceFromObject(line2D10)
    #constraint47 = constraints3.AddBiEltCst(catCstTypeDistance, reference99, reference100)
    #constraint47.Mode = catCstModeDrivingDimension
    #length46 = constraint47.Dimension
    #length46.Value = 27.500000

    
    point2D25 = factory2D3.CreatePoint((c/2), - (c/2))
    point2D25.ReportName = 21
    point2D26 = factory2D3.CreatePoint((c/2), - (c/4))
    point2D26.ReportName = 22
    line2D18 = factory2D3.CreateLine((c/2), - (c/2), (c/2), - (c/4))
    line2D18.ReportName = 23
    line2D18.StartPoint = point2D25
    line2D18.EndPoint = point2D26
    reference101 = part1.CreateReferenceFromObject(point2D25)
    reference102 = part1.CreateReferenceFromObject(line2D11)
    #constraint48 = constraints3.AddBiEltCst(catCstTypeDistance, reference101, reference102)
    #constraint48.Mode = catCstModeDrivingDimension
    #length47 = constraint48.Dimension
    #length47.Value = 27.500000
    reference103 = part1.CreateReferenceFromObject(point2D25)
    reference104 = part1.CreateReferenceFromObject(line2D10)
    #constraint49 = constraints3.AddBiEltCst(catCstTypeDistance, reference103, reference104)
    #constraint49.Mode = catCstModeDrivingDimension
    #length48 = constraint49.Dimension
    #length48.Value = 27.500000
    reference105 = part1.CreateReferenceFromObject(point2D26)
    reference106 = part1.CreateReferenceFromObject(line2D11)
    #constraint50 = constraints3.AddBiEltCst(catCstTypeDistance, reference105, reference106)
    #constraint50.Mode = catCstModeDrivingDimension
    #length49 = constraint50.Dimension
    #length49.Value = 27.500000
    reference107 = part1.CreateReferenceFromObject(point2D26)
    reference108 = part1.CreateReferenceFromObject(line2D10)
    #constraint51 = constraints3.AddBiEltCst(catCstTypeDistance, reference107, reference108)
    #constraint51.Mode = catCstModeDrivingDimension
    #length50 = constraint51.Dimension
    #length50.Value = 13.750000
    point2D27 = factory2D3.CreatePoint((c/2), - (c/2))
    point2D27.ReportName = 24
    point2D28 = factory2D3.CreatePoint((c/4), - (c/2))
    point2D28.ReportName = 25
    line2D19 = factory2D3.CreateLine((c/2), - (c/2), (c/4), - (c/2))
    line2D19.ReportName = 26
    line2D19.StartPoint = point2D27
    line2D19.EndPoint = point2D28
    reference109 = part1.CreateReferenceFromObject(point2D27)
    reference110 = part1.CreateReferenceFromObject(line2D11)
    #constraint52 = constraints3.AddBiEltCst(catCstTypeDistance, reference109, reference110)
    #constraint52.Mode = catCstModeDrivingDimension
    #length51 = constraint52.Dimension
    #length51.Value = 27.500000
    reference111 = part1.CreateReferenceFromObject(point2D27)
    reference112 = part1.CreateReferenceFromObject(line2D10)
    #constraint53 = constraints3.AddBiEltCst(catCstTypeDistance, reference111, reference112)
    #constraint53.Mode = catCstModeDrivingDimension
    #length52 = constraint53.Dimension
    #length52.Value = 27.500000
    reference113 = part1.CreateReferenceFromObject(point2D28)
    reference114 = part1.CreateReferenceFromObject(line2D11)
    #constraint54 = constraints3.AddBiEltCst(catCstTypeDistance, reference113, reference114)
    #constraint54.Mode = catCstModeDrivingDimension
    #length53 = constraint54.Dimension
    #length53.Value = 13.750000
    reference115 = part1.CreateReferenceFromObject(point2D28)
    reference116 = part1.CreateReferenceFromObject(line2D10)
    #constraint55 = constraints3.AddBiEltCst(catCstTypeDistance, reference115, reference116)
    #constraint55.Mode = catCstModeDrivingDimension
    #length54 = constraint55.Dimension
    #length54.Value = 27.500000
    line2D20 = factory2D3.CreateLine((c/4), (c/2), (c/2), (c/4))
    line2D20.ReportName = 27
    line2D20.StartPoint = point2D16
    line2D20.EndPoint = point2D14
    line2D21 = factory2D3.CreateLine(- (c/2), (c/4), - (c/4), (c/2))
    line2D21.ReportName = 28
    line2D21.StartPoint = point2D18
    line2D21.EndPoint = point2D20
    line2D22 = factory2D3.CreateLine(- (c/2), - (c/4), - (c/4), - (c/2))
    line2D22.ReportName = 29
    line2D22.StartPoint = point2D22
    line2D22.EndPoint = point2D24
    line2D23 = factory2D3.CreateLine((c/4), - (c/2), (c/2), - (c/4))
    line2D23.ReportName = 30
    line2D23.StartPoint = point2D28
    line2D23.EndPoint = point2D26
    
    sketch3.CloseEdition()
    part1.InWorkObject = sketch3
    part1.Update()
    viewpoint3D1 = viewer3D1.Viewpoint3D
    viewer3D1.Reframe()
    viewpoint3D1 = viewer3D1.Viewpoint3D
    pocket1 = shapeFactory1.AddNewPocket(sketch3, 27.500000)
    limit3 = pocket1.FirstLimit
    length55 = limit3.Dimension
    length55.Value = g                                                     #g is 1.2kd1
    part1.Update()

    
    
    reference117 = part1.CreateReferenceFromName('Selection_RSur:(Face:(Brp:(Pad.1;2);None:();Cf11:());Pocket.1_ResultOUT;Z0;G3563)')
    sketch4 = sketches2.Add(reference117)
    arrayOfVariantOfDouble4[0] = 0.000000
    arrayOfVariantOfDouble4[1] = a
    arrayOfVariantOfDouble4[2] = 0.000000
    arrayOfVariantOfDouble4[3] = - 1.000000
    arrayOfVariantOfDouble4[4] = 0.000000
    arrayOfVariantOfDouble4[5] = 0.000000
    arrayOfVariantOfDouble4[6] = 0.000000
    arrayOfVariantOfDouble4[7] = 0.000000
    arrayOfVariantOfDouble4[8] = 1.000000
    sketch4.SetAbsoluteAxisData(arrayOfVariantOfDouble4)
    part1.InWorkObject = sketch4
    factory2D4 = sketch4.OpenEdition()                                        #sketch 4 open
    geometricElements4 = sketch4.GeometricElements
    axis2D4 = geometricElements4.Item('AbsoluteAxis')
    line2D24 = axis2D4.GetItem('HDirection')
    line2D24.ReportName = 1
    line2D25 = axis2D4.GetItem('VDirection')
    line2D25.ReportName = 2
    circle2D2 = factory2D4.CreateClosedCircle(0.000000, 0.000000, e)
    point2D29 = axis2D4.GetItem('Origin')
    circle2D2.CenterPoint = point2D29
    circle2D2.ReportName = 3
    constraints4 = sketch4.Constraints
    reference118 = part1.CreateReferenceFromObject(circle2D2)
    #constraint56 = constraints4.AddMonoEltCst(catCstTypeRadius, reference118)
    #constraint56.Mode = catCstModeDrivingDimension
    #length56 = constraint56.Dimension
    #length56.Value = 25.000000
    sketch4.CloseEdition()                                                      #sketch 4 closed
    part1.InWorkObject = sketch4
    part1.Update()
    reference119 = part1.CreateReferenceFromName('')
    pocket2 = shapeFactory1.AddNewPocketFromRef(reference119, 60.000000)
    reference120 = part1.CreateReferenceFromObject(sketch4)
    pocket2.SetProfileElement(reference120)
    limit4 = pocket2.FirstLimit
    length57 = limit4.Dimension
    length57.Value = (2*a)                                             #pad
    part1.Update()
    viewpoint3D1 = viewer3D1.Viewpoint3D
    reference121 = part1.CreateReferenceFromName('Selection_RSur:(Face:(Brp:(Pad.2;0:(Brp:(Sketch.2;11)));None:();Cf11:());Pocket.2_ResultOUT;Z0;G3563)')
    sketch5 = sketches2.Add(reference121)
    arrayOfVariantOfDouble5[0] = - m
    arrayOfVariantOfDouble5[1] = 0.000000
    arrayOfVariantOfDouble5[2] = 0.000000
    arrayOfVariantOfDouble5[3] = 0.000000
    arrayOfVariantOfDouble5[4] = - 1.000000
    arrayOfVariantOfDouble5[5] = 0.000000
    arrayOfVariantOfDouble5[6] = 0.000000
    arrayOfVariantOfDouble5[7] = 0.000000
    arrayOfVariantOfDouble5[8] = 1.000000
    sketch5.SetAbsoluteAxisData(arrayOfVariantOfDouble5)
    part1.InWorkObject = sketch5
    factory2D5 = sketch5.OpenEdition()
    geometricElements5 = sketch5.GeometricElements
    axis2D5 = geometricElements5.Item('AbsoluteAxis')
    line2D26 = axis2D5.GetItem('HDirection')
    line2D26.ReportName = 1
    line2D27 = axis2D5.GetItem('VDirection')
    line2D27.ReportName = 2
    circle2D3 = factory2D5.CreateClosedCircle(0.000000, 0.000000, h)
    point2D30 = axis2D5.GetItem('Origin')
    circle2D3.CenterPoint = point2D30
    circle2D3.ReportName = 3
    constraints5 = sketch5.Constraints
    reference122 = part1.CreateReferenceFromObject(circle2D3)
    #constraint57 = constraints5.AddMonoEltCst(catCstTypeRadius, reference122)
    #constraint57.Mode = catCstModeDrivingDimension
    #length58 = constraint57.Dimension
    #length58.Value = 25.000000
    sketch5.CloseEdition()
    part1.InWorkObject = sketch5
    part1.Update()
    viewer3D1.Reframe()
    viewpoint3D1 = viewer3D1.Viewpoint3D
    pad3 = shapeFactory1.AddNewPad(sketch5, 62.500000)
    limit5 = pad3.FirstLimit
    length59 = limit5.Dimension
    length59.Value = g

    
    part1.Update()
    viewpoint3D1 = viewer3D1.Viewpoint3D
    viewer3D1.Reframe()
    viewpoint3D1 = viewer3D1.Viewpoint3D

knuckles()
